### ISSUE TITLE
issue about PKG

### ISSUE THREAD

**Issue by Matsuri247** [Evangelion09/KNLNet#1]
I try to applied your KNLConv to my own work, but there's something wrong with PKG. Specifically, the class _routing.
![img1](https://github.com/Evangelion09/KNLNet/assets/56073360/ce131cd1-1594-47bb-a90b-a0a1b29d4752)
![img2](https://github.com/Evangelion09/KNLNet/assets/56073360/b1d1edc4-6b75-45af-a278-ca86c74d2ad2)
Actually, pooled_inputs is a value with batch_size. It seems that you ignore it and simply flatten this value. So how can you train the KNLNet with batch_size=32? It is quite confusing. Looking forward to your reply.

**Comment by shaoyouyiyi** [comment]
yo, brother, can you please solve this dimension problem, I'm experiencing a similar problem

**Comment by Evangelion09** [comment]
Thanks, the general model has been updated.
